name: do_frontend
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  http: ^0.13.5
  flutter_secure_storage: ^9.0.0
  fl_chart: 0.36.4
  image_picker: ^0.8.7+4
  cupertino_icons: ^1.0.8
  table_calendar: ^3.0.7 # table_calendar는 dependencies로 옮김
  url_launcher: ^6.0.20


dev_dependencies:
  flutter_launcher_icons: "^0.14.2"

flutter_launcher_icons:
    android: "launcher_icon"
    ios: true
    image_path: "assets/images/man-05.png"
    min_sdk_android: 21 # android min sdk min:16, default 21
    web:
      generate: true
      image_path: "assets/images/man-05.png"
      background_color: "#hexcode"
      theme_color: "#hexcode"
    windows:
      generate: true
      image_path: "assets/images/man-05.png"
      icon_size: 48 # min:48, max:256, default: 48
    macos:
      generate: true
      image_path: "assets/images/man-05.png"

flutter_test:
    sdk: flutter
hive_generator: ^2.0.0
build_runner: ^2.3.3
flutter_lints: ^4.0.0

flutter:
  assets:
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Jua
      fonts:
        - asset: assets/fonts/BMJUA_ttf.ttf

    - family: NanumGothic
      fonts:
        - asset: assets/fonts/NanumGothic-Regular.ttf

    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf

    - family: Roboto1
      fonts:
        - asset: assets/fonts/RobotoFlex-VariableFont.ttf

    - family: RubikScribble
      fonts:
        - asset: assets/fonts/RubikScribble-Regular.ttf

    - family: Dohyeon
      fonts:
        - asset: assets/fonts/BMDOHYEON_ttf (1).ttf

  uses-material-design: true
