name: do_frontend
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  fl_chart: 0.36.4
  image_picker: ^0.8.7+4
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  assets:
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Jua
      fonts:
        - asset: assets/fonts/BMJUA_ttf.ttf

    - family: NanumGothic
      fonts:
        - asset: assets/fonts/NanumGothic-Regular.ttf

    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf

    - family: Roboto1
      fonts:
        - asset: assets/fonts/RobotoFlex-VariableFont.ttf

    - family: RubikScribble
      fonts:
        - asset: assets/fonts/RubikScribble-Regular.ttf

    - family: Dohyeon
      fonts:
        - asset: assets/fonts/BMDOHYEON_ttf (1).ttf

  uses-material-design: true
